# Generated by Django 4.2.14 on 2024-09-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_List_Version_2', '0004_alter_tasks_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Time',
            new_name='time',
        ),
    ]
